pipeline {
  agent any
  environment {
    IMAGE_NAME = "hello-world-gui"
    IMAGE_TAG = "latest"
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'master', url: 'https://github.com/k-patidar/covid19-treaker.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        echo 'Building Docker image from backend/Dockerfile...'
        sh 'docker build -t hello-world-gui:latest -f backend/Dockerfile backend'
      }
    }

    stage('Stop Old Container') {
      steps {
        echo 'Stopping old container (if exists)...'
        sh 'docker rm -f hello-world-gui || true'
      }
    }

    stage('Run Container') {
      steps {
        echo 'Running new container on port 5000...'
        sh 'docker run -d -p 5000:5000 --name hello-world-gui hello-world-gui:latest'
      }
    }
  }

  post {
    failure {
      echo ' Build failed. Check logs and Dockerfile path.'
    }
    success {
      echo ' Build and container run successful!'
    }
  }
}




